version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: notas-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notas-network

networks:
  notas-network:
    driver: bridge

volumes:
  postgres_data:
